### ISSUE TITLE
Solid NavBar

### ISSUE THREAD

**Issue by soniaprueba2** [pyro2927/ParallaxBlur#10]
When the navBar is "transparent = NO" the view has an odd behave scrolling up and down

how can i solve this? 
![img_1023](https://cloud.githubusercontent.com/assets/4153896/5046672/88f3ddba-6bdf-11e4-9db4-c7cf3b25f844.PNG)
![img_1024](https://cloud.githubusercontent.com/assets/4153896/5046673/88f42270-6bdf-11e4-84a8-5b2f65c13126.PNG)

**Comment by pyro2927** [comment]
Thanks! Fix in 33c52c121d407c9fd77c13dc67619d8c16390963
